# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.
        bind:
            $linkedInToken: "%env(string:LINKEDIN_TOKEN)%"
            $linkedInUserId: "%env(string:LINKEDIN_USER_ID)%"
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Social\DraftShareContent:
        tags: ['social_network']

    App\Social\LinkedinShareContent:
        tags: ['social_network']

    App\Resolver\:
        resource: '../src/Resolver'
        tags: ['overblog_graphql.resolver']

    planet.resolver:
        alias: App\Resolver\PlanetResolver
        public: true

    App\Mutation\:
        resource: '../src/Mutation'
        tags: ['overblog_graphql.mutation']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
